### ISSUE TITLE
Unable to open Events link as the connection could not be authenticated

### ISSUE THREAD

**Issue by sagunase** [Azure-Samples/azure-iot-edge-identity-translation-lite#15]
**Setup**

1. Installed IoT Edge Runtime in Linux container on windows 10 machine
2. Registered IoT edge in IoT Hub and created few leaf devices as child devices under this parent device

**Steps to Reproduce**

1. Created Signed Key using SignAsync Method
2. Created DeviceClient using signed key, Iot Hub hostname & gateway name for one of the leaf device
3. On Sending the message to using DeviceClient, getting below error.

**Stack Trace:**

Unhandled Exception: System.AggregateException: One or more errors occurred. (error(condition:amqp:not-allowed,description:Unable to open Events link as the connection could not be authenticated)) ---> System.InvalidOperationException: error(condition:amqp:not-allowed,description:Unable to open Events link as the connection could not be authenticated) ---> Microsoft.Azure.Amqp.AmqpException: Unable to open Events link as the connection could not be authenticated

at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)

at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)

at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)

at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenSendingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String CorrelationId, TimeSpan timeout)

--- End of inner exception stack trace ---

at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenSendingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String CorrelationId, TimeSpan timeout)

at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenTelemetrySenderLinkAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)

at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)

at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)

at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)

at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)

at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)

at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)

at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)

at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)

at IdentityTranslationLite.Program.PushMessages() in /app/Program.cs:line 107

at IdentityTranslationLite.Program.Init() in /app/Program.cs:line 84

--- End of inner exception stack trace ---

at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

at System.Threading.Tasks.Task.Wait()

at IdentityTranslationLite.Program.Main(String[] args) in /app/Program.cs:line 42

**Comment by sagunase** [comment]
I figured out the issue, I created leaf devices directly in Azure Portal with Auto SymmetricKey generated and i am trying to sign using ModuleId's symmetric key to generate symmetric key for leaf devices. 
Closing this issue.
